[gemini]
api_key = "AIzaSyBtoDqSWKbhemG8RPnxYwJ-JUUU2DSrBdQ"

[generation]
api_key = "YOUR_GEMINI_API_KEY"

[firebase]
project_id = "your-project-id"
private_key_id = "your-private-key-id"
private_key = "-----BEGIN PRIVATE KEY-----\nYOUR_KEY\n-----END PRIVATE KEY-----\n"
client_email = "firebase-adminsdk@your-project-id.iam.gserviceaccount.com"
client_id = "your-client-id"

