[gemini]
api_key = "AIzaSyBtoDqSWKbhemG8RPnxYwJ-JUUU2DSrBdQ"

[generation]
api_key = "YOUR_GEMINI_API_KEY"

[firebase]
type = "service_account"
project_id = "engineering-maths-app"
private_key_id = "1234567890abcdef1234567890abcdef12345678"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvAIBADANBgkqh...
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-xyz@engineering-maths-app.iam.gserviceaccount.com"
client_id = "123456789012345678901"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk"



