[gemini]
api_key = "AIzaSyBtoDqSWKbhemG8RPnxYwJ-JUUU2DSrBdQ"

[generation]
api_key = "YOUR_GEMINI_API_KEY"

GOOGLE_API_KEY = "your_api_key_here"

[firebase]
type = "service_account"
project_id = "engineering-maths-app"
private_key_id = "7c14b70c0933227392732e8c43b0a067c7295600"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDZ0Cd5YwOnr2OT\n4m3hY//5ChcTTLcYSOrKHNrujANUgeBhIxke3CTLRdDA5Ab7u2qgzHwdL/y3yxHD\n3NWUBrsRnL78TE9ED3F8KAB1Ft6G4jjmdeQ881K4wJb5nzIKKJZDdhpBnLJ6OUic\n6SAmW1gh1d3UwWWDYJEC/5Ar9ENYyW4BiJXgftrQrBCLEe7SZPmkBfREP3jBBq0s\nJRqC+AeaKeCFaDIaXp8PgciIw0zO0RrIsANQFXK2l0o+Rb+fhZJ7P7NGdHgJM9VR\nMp/Ge9BTcMhLJffAdrzrdnBSOFQpsZiFCi9uNnGFFwGhEhFM9WrnrwCd8B86621i\nwoGhZ3dPAgMBAAECggEAHcU3F/7CCaHNxPE+Xn+aBXJtG/ywy9dvi+dsvw0RCXRk\n9DHlZZPmTYhB05N3JuIDXW4FisG7020khPZClORknjAj5H0TmnRX6QXYpihViu8R\nouI7K1+Aj3L3T7AEGWJZw2e5h/1AYbdBpvywIb37akh+dO1oEBBbUaMXlAJjUBeb\nV2DQ8EoZdMeTGTlarBs1BQWqiNHH2qc9yugUJ3qXSklV2fZgQsGal33m0kpjMWsb\nmbNkvuEuFbU7oqjefPtdhOs1uVjgqEZBZQ8dAkef/xyGLYfb6nLrXZ7uxtGfsuFT\n1tb0yuxgJ+n2R8zgoXYS7ItG+F+nM7Fguy7LRTKd4QKBgQD42zGVGS/4W5AOc1qW\npUaLqwDlqAGx6kjCYS/G8E+LrrDNfQyb4YZfZV/NxBvRuT8ad79KaZQRu2D1F8ya\nm2thZslJrBJmRIeoIGJqH5WiQiD/BX6w9dIAVrVikaALeSMAO5Kbtf5gRTKAWWqR\nk7wmqkC5i3VfhVGcBXvIhBTqrwKBgQDgENRQjhAAvaSfByQ4e5nyN6VtxA7F3nhI\n9Sx7o7oyEvr6Y4FZHZHOB7dXQopfhmSo02fMxQMv/9jpOSZU4GHawxN+wAw+zheL\nZMjkLNUq1NZJcvqziqxYFJh1qOtvaiahirvoFuXT8ECyVDXegwCyaQI0RuP9h/Fm\nzegvDDTlYQKBgQDztgaK1A3slg8wd7wByH6cDa5lOvHeAWmcI32cwH/GdiBkPdD5\nYBYumqMGasYrz9WC4D8QavE9pFpB7TrNNuQkkXsTkVa7nOWVu5FmCOSL8WNLHWCD\ngVpWRpSAockxM0MZ2T2tDMDAG0Rn+impxBsBar7Ud0VNdM0FlUEykFfDtQKBgQC7\nS5YOGBIsbFm1TQTr6fXPUNCJpn8qy0IEylx6pWu4+8CrmI3A7kS40h5hZI/CNdbi\ngISd2HlHoDezDECMZlulv7cGFoal4SQxMvfyM7+kY/ETyHbjqaFSpzSh9aeHpFXS\nZuOXp7xJouSRrG6zJxJoD/r1s+RUQ1R4uNnCqhN1QQKBgQCqki1SNqzCBc2UTgR2\nrBHZM8WU2AouidiU+/SM/2IWN3WLdZyVj5tawY7O0e41PX4vHvjuf170GhFu7i/2\nZBuNiYeQJTUe6ofAgnf2YG0uLrduW4i2o03Hy7Ev0nHX+xb+T8tObuM/NyKFpC6Y\nFe3eb31d0YbeFXR6nmmxGtJ63g==
-----END PRIVATE KEY-----"""
client_email = "firebase-adminsdk-fbsvc@engineering-maths-app.iam.gserviceaccount.com"
client_id = "115404201099853336801"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40engineering-maths-app.iam.gserviceaccount.com"
universe_domain = "googleapis.com"



